### ISSUE TITLE
打包后页面无法显示

### ISSUE THREAD

**Issue by ccdeville** [necrodiver/HospitalAutoRegister#10]
您好，使用过程中有一些疑问
npm run dev或直接用iis加载dist 可以看到前端页面
npm run build 后运行go build出的exe文件页面无法显示
以下是F12 结果
失败情况
![failed](https://user-images.githubusercontent.com/19767558/155963044-80f1a357-7fb3-491d-b64f-e7dc6fa77aa3.png)
成功情况
![sucess](https://user-images.githubusercontent.com/19767558/155963075-eacdb73b-ff2b-4d68-af3f-cc7627c6f536.png)
我对vue和vite不是很了解，还请帮忙

**Comment by necrodiver** [comment]
你好，看起来你使用的是windows系统，而且这个network输出没问题，这里看一下如果使用命令 go run main.go能否访问到呢？，请提前关闭npm run dev的启用。
如果可以，打包是没问题的，注意此打包不会把dist文件夹一块打包到exe内，可以查看go启动的命令窗口输出，看看能发现什么，dist文件夹内的文件是静态的，在gin引用dist文件时请查看是否存在错误，这里我抽空看一下。

**Comment by ccdeville** [comment]
看起来和平台有关 ，我重新在linux下编译没有问题

**Comment by necrodiver** [comment]
好吧，后边我再看一下其他平台，应该和gin插件对文件的引用方式有关系
