### ISSUE TITLE
panic: html/template: pattern matches no files: `./app/dist/*.html`

### ISSUE THREAD

**Issue by 8955107** [necrodiver/HospitalAutoRegister#11]
![image](https://user-images.githubusercontent.com/62317011/161037043-8f376c66-afa0-4296-8ef1-0e9059a8a946.png)
我在运行的时候出现的panic: html/template: pattern matches no files: `./app/dist/*.html`的问题

**Comment by rojarifiroj** [comment]
出现同样的问题，请问楼主如何解决的？
