### ISSUE TITLE
各位有比较好的能获得登录token的方法吗？

### ISSUE THREAD

**Issue by necrodiver** [necrodiver/HospitalAutoRegister#14]
先抛砖引玉一下，开始研究并想着如何自动化去挂号，有四种方案：
1. 第一种方案，完全模拟登录，本地实现登录，参照智行挂12306的车票，不过这种难度比较大，个人技术也就这样了，需要扒微信这套安全机制，排除吧；  
2. 第二种方案，比较好用的就是windows系统，直接抓pc端小程序内部存储堆栈，windows的以前也接触过这种抓取及注入，需要去研究，暂定最后吧，mac尝试了一下，抓的我头疼；  
3. 第三种方案，内部集成一套抓包插件，然后自动解析抓取登录token，自动填充到请求接口中，但是这个需要做代理，使用代理去中转，在中转的时候解析数据，要我从头开始造轮子实现这个不大现实（技术也就这样了），然后这种抓包的就搁浅了，暂时还未找到对应的插件；  
4. 第四种方案，比较简单了，比如windows系统fiddler内部提供自定义脚本（js或者C#），把抓包解析的内容使用脚本传到当前程序中，也能达到效果，不过这种比较受限于需要安装其他的抓包工具并手动配置，对使用者来说很不友好，各位想搞的话可以试试，当前项目的功能完全支持这套方案； 
以上方案能够广泛使用的我认为第三种比较好了，不仅仅是当前程序中能够OK，以后其他的挂号都OK，各位有其他好的思路吗？或者能够提供一份能够实现的方案？

**Comment by haogong** [comment]
感觉自己抓包获得token已经是相对比较容易的了。自动获取难度确实有点大，楼主如果太复杂可以不用实现，我个人认为

**Comment by necrodiver** [comment]
> 感觉自己抓包获得token已经是相对比较容易的了。自动获取难度确实有点大，楼主如果太复杂可以不用实现，我个人认为

从普通人的角度考虑，这个使用门槛有点高了，从开发者角度考虑，愿意动手搜一搜都能够跑起来
