### ISSUE TITLE
小程序上看有医生可以预约，但这个程序运行时显示该日期不可选择

### ISSUE THREAD

**Issue by haogong** [necrodiver/HospitalAutoRegister#15]
![image](https://user-images.githubusercontent.com/11763901/163659370-e98a5f12-cf42-4f59-9415-d65ef64edd9a.png)
如上。

测试时选择的是第四门诊部（第四门诊部余号多，平时有机会约到，其它大部分都靠抢，约不到）
每一个科室都不可选择。
测试时间：4月16日
小程序显示4月18日可以预约，但网页上显示都不可选择。麻烦看一下为什么，是bug吗？

**Comment by necrodiver** [comment]
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/13930551/163746684-91cf21c4-04cc-4b4a-b75e-6bb0d8e93152.png">
不好意思，回复晚了，不知道小程序这块改了导致的还是原本这块就有问题，原本应该是没问题的，如果你比较急，可以fork后自己在目录:app>src>views>Index>components>Step4.jsx我所截图这块修改，晚点我会更新本次修改

**Comment by necrodiver** [comment]
已经提交了
