### ISSUE TITLE
求助(无奈表情...)

### ISSUE THREAD

**Issue by HouWan** [necrodiver/HospitalAutoRegister#16]
在GitHub上看到了您的项目，我深受口腔牙齿问题困扰，所以想咨询下大哥北大口腔的问题。

但是项目完美避开了我的技术栈，所以能否wx交流一下，哎~我想改成Python来解决牙的问题，咨询种植牙居然要8000起步。。

**Comment by necrodiver** [comment]
你好，如果你想咨询技术问题，可以先看一下readme，从入口出发，耐心看一下（这个库所解决的可能并不能让你很快的去挂到号，不要被），把对应接口转换成python，模拟请求，使用核心的wxutil.js内的方法加解密，python应该有对应的运行js代码的库
