### ISSUE TITLE
本地运行请求api 代理到 go本地服务上, 解析报错

### ISSUE THREAD

**Issue by XiaoLiz** [necrodiver/HospitalAutoRegister#17]

**Comment by necrodiver** [comment]
不好意思，最近没有稳定下来(你懂的，最近国内行情导致我领了大礼包，而且在写另一个开源库，暂时没空啊兄弟，所以暂时不会去修复这个问题)，如果有问题请务必首先排除之前历史已关闭的issues，如果有加解密出错问题，请务必查看是否是你的参数输入的存在问题，最后就是北大口腔的小程序更新过，改过加解密方法了，这里提供一下当前小程序的解包方法，反解包工具：https://github.com/xuedingmiaojun/wxappUnpacker（这个作者也隐藏了他的代码，你需要看readme），反解密方法：http://xuedingmiao.com/blog/xcx_unpack.html，其中反解密方法的使用请按照这样的操作查看，因为这是别人整理的，之前是开放的，现在不开放了，说一下怎么处理这个扫二维码的（不是让你加他，是怎么绕过这个二维码），看下图，打开站点，然后按F12（或者右键点击检查），开发者工具上切换到**Elements**，找到下图对应的位置，然后有两个操作，第一个是去掉id为main-content的的高度限制，第二个是干掉这个弹框的我标红的前端代码，，再关掉开发者工具，然后你就可以自学这个解包工具了
![image](https://user-images.githubusercontent.com/13930551/192221028-b092ed15-5b17-40fb-8946-8538c203ddbd.png) ，最后就是分析代码了，你所抓取的登陆token是可以种进去的，可能这里分析就很复杂了，哎，这希望你能琢磨出来，至于具体实际操作可能得另出一篇文章了，暂时没空啊兄弟，真没空，这个你要是解决了可以分享一下结果再关闭这个issue，非常感谢，等我稳定了也会着手解决

**Comment by necrodiver** [comment]
不好意思，最近没有稳定下来(你懂的，最近国内行情导致我领了大礼包，而且在写另一个开源库，暂时没空啊兄弟，所以暂时不会去修复这个问题)，如果有问题请务必首先排除之前历史已关闭的issues，如果有加解密出错问题，请务必查看是否是你的参数输入的存在问题，最后就是北大口腔的小程序更新过，改过加解密方法了，这里提供一下当前小程序的解包方法，解包工具：[https://github.com/xuedingmiaojun/wxappUnpacker](https://github.com/xuedingmiaojun/wxappUnpacker)（这个作者也隐藏了他的代码，你需要看readme），反解密方法：[http://xuedingmiao.com/blog/xcx_unpack.html](http://xuedingmiao.com/blog/xcx_unpack.html)，其中反解密方法的使用请按照这样的操作查看，因为这是别人整理的，之前是开放的，现在不开放了，说一下怎么处理这个扫二维码的（不是让你加他，是怎么绕过这个二维码），看下图，打开站点，然后按F12（或者右键点击检查），开发者工具上切换到**Elements**，找到下图对应的位置，然后有两个操作，第一个是去掉id为main-content的的高度限制，第二个是干掉这个弹框的我标红的前端代码，，再关掉开发者工具，然后你就可以自学这个解包工具了
![image](https://user-images.githubusercontent.com/13930551/192221028-b092ed15-5b17-40fb-8946-8538c203ddbd.png) ，最后就是分析代码了，你所抓取的登陆token是可以种进去的，可能这里分析就很复杂了，哎，这希望你能琢磨出来，至于具体实际操作可能得另出一篇文章了，暂时没空啊兄弟，真没空，这个你要是解决了可以分享一下结果再关闭这个issue，非常感谢，等我稳定了也会着手解决

**Comment by ZhangWren** [comment]
@necrodiver 大佬大概什么时候才能有时间解决一下，实在是改不动，本人一点Go都不会，硬着头皮对照着小程序解包后的文件对了一周，无奈技术有限，始终不得要领，号实在是难挂，求助求助

**Comment by necrodiver** [comment]
@Lukeeeeeeeeee 最近确实没空，很多事都耽搁了，得一件件处理，计划赶不上变化，顺利的话应该很快，go只是其中一种方案，代码的话熟悉js也差不多，把它当成js就行。
主要针对看的是DecryStr方法，这里边调用的那个js和解密方法一样，针对性的替换一下，可能有些调整，其他的不用管，在解包后的文件里边找到和[wxutil.js](https://github.com/necrodiver/HospitalAutoRegister/blob/main/utils/js/wxutil.js)一样的文件名，查看4711行的代码（也就是CC方法），顶部引用的：s = CryptoJS(), c = Base64JS()，这两个的CryptoJS和Base64JS是其他文件中引用过来的，你可以提取出去对比最新的看看（这两个应该改动概率很小，哈哈我现在只能虚空分析）这两个方法先摘除，内部文件就很小了。

**Comment by Lukeeeeeeeeee** [comment]
> @Lukeeeeeeeeee 最近确实没空，很多事都耽搁了，得一件件处理，计划赶不上变化，顺利的话应该很快，go只是其中一种方案，代码的话熟悉js也差不多，把它当成js就行。 主要针对看的是DecryStr方法，这里边调用的那个js和解密方法一样，针对性的替换一下，可能有些调整，其他的不用管，在解包后的文件里边找到和[wxutil.js](https://github.com/necrodiver/HospitalAutoRegister/blob/main/utils/js/wxutil.js)一样的文件名，查看4711行的代码（也就是CC方法），顶部引用的：s = CryptoJS(), c = Base64JS()，这两个的CryptoJS和Base64JS是其他文件中引用过来的，你可以提取出去对比最新的看看（这两个应该改动概率很小，哈哈我现在只能虚空分析）这两个方法先摘除，内部文件就很小了。

![image](https://user-images.githubusercontent.com/25240164/199882428-45387437-08eb-4970-af59-46dcd5d436d1.png)
大佬，这个报错应该怎么解决，我解决了前面的加解密报错，但是到第二部院区选择卡住了，我抓小程序接口也没抓出个所以然，大佬写的那些代理接口我一个都没抓出来，不知道怎么往下走了，请大佬帮帮忙

**Comment by ZhangWren** [comment]
@necrodiver 这种报错怎么结局，大佬
![image](https://user-images.githubusercontent.com/25240164/199933209-b22f39f1-9830-4362-b48c-71630c80a576.png)

**Comment by necrodiver** [comment]
@Lukeeeeeeeeee 不知道哇，签名错误，要么就是登录token过期了，要么参数错了，要么就是封号了。解密解决了么

**Comment by ZhangWren** [comment]
@necrodiver 第一步搞定了，现在卡在第二步，就是这个签名错误，不知道咋解决了。我PR了，你看看

**Comment by ZhangWren** [comment]
> @necrodiver 第一步搞定了，现在卡在第二步，就是这个签名错误，不知道咋解决了。我PR了，你看看

我抓包最新的参数，token应该没有过期，然后我去小程序看了下，我的号也是没啥问题的，那应该是参数的问题了

**Comment by necrodiver** [comment]
@Lukeeeeeeeeee 封号指的是你在所有时间能够看到有号的情况下，选择挂号都会提示你挂不上

**Comment by ZhangWren** [comment]
> @Lukeeeeeeeeee 封号指的是你在所有时间能够看到有号的情况下，选择挂号都会提示你挂不上

没有问题，我试了下，可以正常挂号预约付钱

**Comment by lvxinliang** [comment]
在网页输入了正确的三个信息，点击“解析”后出现下面报错，清楚是什么问题吗？请教一下
```
2023/02/15 16:05:24 [Recovery] 2023/02/15 - 16:05:24 panic recovered:
POST /api/analysis HTTP/1.1
Host: 127.0.0.1:10087
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6
Connection: keep-alive
Content-Length: 1878
Content-Type: application/json
Origin: http://127.0.0.1:10087
Referer: http://127.0.0.1:10087/
Sec-Ch-Ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36


Error: Malformed UTF-8 data
/Users/lvxinliang/workspace/HospitalAutoRegister/utils/EncryDecryHelper.go:50 (0x15494de)
	DecryStr: panic(err)
/Users/lvxinliang/workspace/HospitalAutoRegister/utils/InitGinHelper.go:42 (0x154a9fd)
	InitGin.func2: str := DecryStr(USER_SIGN, USER_ENCRY)
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x153cbc1)
	(*Context).Next: c.handlers[c.index](c)
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x153cbac)
	CustomRecoveryWithWriter.func1: c.Next()
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x153bd26)
	(*Context).Next: c.handlers[c.index](c)
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x153bd09)
	LoggerWithConfig.func1: c.Next()
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x153adea)
	(*Context).Next: c.handlers[c.index](c)
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x153aa71)
	(*Engine).handleHTTPRequest: c.Next()
/Users/lvxinliang/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x153a591)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2936 (0x12df6d5)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1995 (0x12dabf1)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1598 (0x1066340)
	goexit: BYTE	$0x90	// NOP
```

**Comment by necrodiver** [comment]
@lvxinliang 经过测试，小程序已经有2次或者多次修改加密解密方法，所以这块单纯的更换加解密可能需要其他方案，或者一直跟随小程序去解包，去分析

**Comment by lvxinliang** [comment]
> @lvxinliang 经过测试，小程序已经有2次或者多次修改加密解密方法，所以这块单纯的更换加解密可能需要其他方案，或者一直跟随小程序去解包，去分析

了解，感谢。就是参考上面👆这个方式吧。-->反解密方法：http://xuedingmiao.com/blog/xcx_unpack.html

**Comment by hhheroo** [comment]
@lvxinliang @Lukeeeeeeeeee  看了一下解密比较简单 加了个内置密钥，同时修改了字符串拼接的方式
```js
const o = require('./cryptojs')

const D = function (A) {
  return o.MD5(A.toString()).toString();
};

const x = function (A) {
  return Array.from(m(A)).reverse().join('');
};

const v = function (A) {
  return null == A || null == A;
};

const m = function (e) {
  var t = arguments.length > 1 && void 0 !== arguments[1] ? arguments[1] : '';
  return v(e) ? t : 'object' == typeof e ? JSON.stringify(e) : e.toString();
};

const B = function (A, e) {
  var t = o.enc.Utf8.parse(e.toString()),
    n = o.enc.Utf8.parse(x(e.toString())),
    i = o.AES.decrypt(A.toString(), t, {
      iv: n,
      mode: o.mode.CBC,
      padding: o.pad.Pkcs7
    });
  return o.enc.Utf8.stringify(i);
};

const apiSecret = 'vGpN60+B%VldZrJxMTm~PdKa$p9-4&z1';

function decrypt(sign, encStr) {
  for (
    var a = D(x(sign + ':' + apiSecret))
        .substring(8, 24)
        .toUpperCase()
        .split(''),
      o = 0;
    o < a.length / 2;
    o++
  ) {
    var s = a[2 * o];
    (a[2 * o] = a[2 * o + 1]), (a[2 * o + 1] = s);
  }
  var u = a.join(''),
    c = encStr;

  return B(c, u);
}
```

**Comment by Geometry6151** [comment]
按照 @hhheroo 提供的代码，把 wxutil.js 的 4508 行 改成
`var r = A.header['x-sign'] + ':vGpN60+B%VldZrJxMTm~PdKa$p9-4&z1' || '',`
就可以了，感谢 @hhheroo

**Comment by Geometry6151** [comment]
找到wxutil.js的`r.push('timestamp=' + n)`所在代码块，把相应的代码改成下面的代码就可以跑起来了
```
r.push('timestamp=' + n), r.push('nonce=' + t), r.push("key=vGpN60+B%VldZrJxMTm~PdKa$p9-4&z1");
        var i = r.join('&'),
            aa = Z(n + "@@vGpN60+B%VldZrJxMTm~PdKa$p9-4&z1"),
            bb = Z(t + "@@vGpN60+B%VldZrJxMTm~PdKa$p9-4&z1"),
            cc = U(i);
        return Z('[' + aa + '#' + Z(cc) + '#' + bb + ']');
```

**Comment by gebizhuxiaowang** [comment]
@Geometry6151  token解析那一步过了之后，后续获取科室，一直报 `请求结果--错误：map[message:访问受限 status:1000]`

> 找到wxutil.js的r.push('timestamp=' + n)所在代码块，把相应的代码改成下面的代码就可以跑起来了

把你后续的内容也照搬过去，也不行；求支持？

**Comment by Geometry6151** [comment]
@gebizhuxiaowang 还有一些别的坑：
1. 访问受限是x-sign，x-version这些过期了，重新抓一个就可以
2. go没有映射worker.js
3. 前端要改一下时间下拉框可选，不然不能到下一步去
4. 现在小程序不能查询还没放出的号的时间段，所以要抢的话还得自己写个py脚本去请求go，我十二点抢到了，就是现在项目的结构特别乱，但是我也没精力改，能用就行。
5. 还有问题就加我wx吧 Geometry6151

**Comment by songhongguang** [comment]
永久还是临时封号？

**Comment by mayongze** [comment]
有人用这个项目挂号成功过么
测试了几天发现挂号并不是比谁速度快, 0s进去提交预约请求一样挂不上
个人几点猜测:
- 挂号系统并不是时间优先胜出机制
- 黑号机制的存在同时只能申请1个医生, 多申请无效
- 每个预约请求耗时都会很长(预约的实现机制可能是随机模式)

看个牙太难了, 一个多礼拜了都还没挂上....有想研究的朋友可以交流下经验

**Comment by HunterGod** [comment]
![image](https://github.com/necrodiver/HospitalAutoRegister/assets/32350173/824af31f-99a6-459b-acc7-72b1405e5fbd)
为什么一直返回这个错，是因为什么吗

**Comment by Kmiracler** [comment]
> @Geometry6151 token解析那一步过了之后，后续获取科室，一直报 `请求结果--错误：map[message:访问受限 status:1000]`
> 
> > 找到wxutil.js的r.push('timestamp=' + n)所在代码块，把相应的代码改成下面的代码就可以跑起来了
> 
> 把你后续的内容也照搬过去，也不行；求支持？

@gebizhuxiaowang 请问下这个问题解决了吗，遇到了相同的问题

**Comment by HunterGod** [comment]
> @necrodiver 这种报错怎么结局，大佬 ![image](https://user-images.githubusercontent.com/25240164/199933209-b22f39f1-9830-4362-b48c-71630c80a576.png)

这个问题你解决了吗 @Lukeeeeeeeeee

**Comment by gebizhuxiaowang** [comment]
@Kmiracler 没有解决，最后通过手动（第一门诊）的方式挂的号，提前选号科室，医生，定好闹钟蹲点。或者每天下午五点抢退号；

**Comment by HunterGod** [comment]
> 有人用这个项目挂号成功过么 测试了几天发现挂号并不是比谁速度快, 0s进去提交预约请求一样挂不上 个人几点猜测:
> 
> * 挂号系统并不是时间优先胜出机制
> * 黑号机制的存在同时只能申请1个医生, 多申请无效
> * 每个预约请求耗时都会很长(预约的实现机制可能是随机模式)
> 
> 看个牙太难了, 一个多礼拜了都还没挂上....有想研究的朋友可以交流下经验

大佬遇到过这个问题吗
![image](https://github.com/necrodiver/HospitalAutoRegister/assets/32350173/fd7194f5-5faf-418d-bb3a-7b6928e90d98)

**Comment by Kmiracler** [comment]
> > 有人用这个项目挂号成功过么 测试了几天发现挂号并不是比谁速度快, 0s进去提交预约请求一样挂不上 个人几点猜测:
> > 
> > * 挂号系统并不是时间优先胜出机制
> > * 黑号机制的存在同时只能申请1个医生, 多申请无效
> > * 每个预约请求耗时都会很长(预约的实现机制可能是随机模式)
> > 
> > 看个牙太难了, 一个多礼拜了都还没挂上....有想研究的朋友可以交流下经验
> 
> 大佬遇到过这个问题吗 ![image](https://user-images.githubusercontent.com/32350173/254286055-fd7194f5-5faf-418d-bb3a-7b6928e90d98.png)

我也卡这了，签名和小程序一致，但是返回签名错误

**Comment by zenyanxiao1** [comment]
> 有人用这个项目挂号成功过么 测试了几天发现挂号不比谁速度快，0s入口提交预约请求同样挂不上 个人几点猜测：
> 
> * 挂号系统并非时间优先胜出机制
> * 黑号机制的存在只能申请1个医生，多申请无效
> * 每个预约请求运行都会很长（预约的实现机制可能是随机模式）
> 
> 看个牙太难了，一个多礼拜都还没挂上....有想研究的朋友可以交流下经验

兄弟你是写脚本跑的吗?

**Comment by zenyanxiao1** [comment]
目前有源码, 但是不知道怎么分析, 调试不了,有大佬懂的吗
