### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yang2632** [necrodiver/HospitalAutoRegister#18]
![image](https://user-images.githubusercontent.com/116134061/197978543-fe078518-1539-4ee9-a950-3e79d0ac5365.png)
小白一个，想给自己挂个号。
请问这个报错可能是什么原因呢。

**Comment by necrodiver** [comment]
看代码就是解密这个地方出了问题，DecryStr方法，查看另一篇issue看看，不好意思，最近没空 
 
[https://github.com/necrodiver/HospitalAutoRegister/issues/17](https://github.com/necrodiver/HospitalAutoRegister/issues/17)
@rojarifiroj
