### ISSUE TITLE
确认下，现在是不是程序已经不可用了？因为小程序加解密变化了吗？

### ISSUE THREAD

**Issue by Mrfuture1** [necrodiver/HospitalAutoRegister#23]

**Comment by necrodiver** [comment]
是的，本来这个问题不想直接摊开说明，但是大多数人的开源精神并不透彻，没有人能主动提出解决，就算解决了也不会公开，所以加解密问题我暂时不会去着手解决，最后就是很多人利用这个去获利，这也不是我的初衷

**Comment by Mrfuture1** [comment]
提个建议，补充一下页面说明。
1. 程序目前不可用，因小程序更新加密
2. 说明一下，程序运行命令，及可浏览器配置参数。

将极大方便大家入门和进一步改善。我就是没接触过vue和go，搞得云里雾里，但实际上用起来很简单，程序前后端用途明确。

**Comment by Mrfuture1** [comment]
> 提个建议，补充一下页面说明。
> 
> 1. 程序目前不可用，因小程序更新加密
> 2. 说明一下，程序运行命令，及可浏览器配置参数。
> 
> 将极大方便大家入门和进一步改善。我就是没接触过vue和go，搞得云里雾里，但实际上用起来很简单，程序前后端用途明确。

没有第二点的说明，极大浪费大家的试用摸索时间。最后还是感谢代码分享

**Comment by necrodiver** [comment]
如果你有其他语言的底子，看代码还是很简单的，核心文件wxutil.js，然后根据go语言所用的模拟请求，用其他语言完全能够搞定，还有一堆的历史issue，我稍微改一下readme吧，谢谢建议
