### ISSUE TITLE
参与共建

### ISSUE THREAD

**Issue by mayongze** [necrodiver/HospitalAutoRegister#25]
能否加个联系方式

**Comment by necrodiver** [comment]
你好，很高兴能够一同建设，如果你想咨询相关流程，可以参考历史issue，全套流程都有解决方案，你可以fork或者提交合并请求来解决现有已知问题，应该没有涉及到技术盲区，若有技术需要的话可以在这里给你文字解决，希望能够理解～～（主要以牟利为目的找我也不少，so～）

**Comment by necrodiver** [comment]
你好，很高兴能够一同建设，如果你想咨询相关流程，可以参考历史issue，全套流程都有解决方案，你可以fork或者提交合并请求来解决现有已知问题，应该没有涉及到技术盲区，若有技术需要的话可以在这里给你文字解决，希望能够理解～～（主要以牟利为目的找我也不少，so～）
