### ISSUE TITLE
一直再报这个签名错误，加密的x-sign和小程序是一样的，在微信小程序就可以请求成功

### ISSUE THREAD

**Issue by HunterGod** [necrodiver/HospitalAutoRegister#27]
![1688697292558](https://github.com/necrodiver/HospitalAutoRegister/assets/32350173/f2bb35a8-cc4d-4aea-9f2b-30af8ee23bb8)

**Comment by zenyanxiao1** [comment]
兄弟,能留个联系方式讨论下吗

**Comment by zenyanxiao1** [comment]
> ![1688697292558](https://user-images.githubusercontent.com/32350173/251621062-f2bb35a8-cc4d-4aea-9f2b-30af8ee23bb8.jpg)

兄弟,能留个联系方式讨论下吗

**Comment by necrodiver** [comment]
https://github.com/necrodiver/HospitalAutoRegister/issues/28
这个，看我回答
