### ISSUE TITLE
请问会出逆向解密和解密的思路吗

### ISSUE THREAD

**Issue by zenyanxiao1** [necrodiver/HospitalAutoRegister#28]

**Comment by zenyanxiao1** [comment]
有最新的源码,不知道怎么分析,...大佬能指导下吗

**Comment by necrodiver** [comment]
可以的话发个最新小程序包（能反编译的），源码更好，最近换电脑了，解不了

**Comment by zenyanxiao1** [comment]
> 可以的话发个最新小程序包（能反编译的），源码更好，最近换电脑了，解不了

大佬, 发你哪里? 联系方式给个,

**Comment by necrodiver** [comment]
https://github.com/necrodiver/HospitalAutoRegister/issues/28#issuecomment-1695492088
发我这个，换了mac，之前的都没了，sixth6rhapsody@gmail.com

**Comment by necrodiver** [comment]
发我这个，换了mac，之前的都没了，sixth6rhapsody@gmail.com，最新的就行，源码和小程序包都给一下

**Comment by rizaust** [comment]
要不要拉个微信群？

**Comment by zenyanxiao1** [comment]
> 发我这个，换了mac，之前的都没了，[sixth6rhapsody@gmail.com](mailto:sixth6rhapsody@gmail.com)，最新的就行，源码和小程序包都给一下

已发

**Comment by zenyanxiao1** [comment]
> 发我这个，换了mac，之前的都没有了，[six6rhapsody@gmail.com](mailto:sixth6rhapsody@gmail.com)，最新的就行，源码和小程序包都给一下

邮件地址不对:

找不到地址
--
由于系统找不到电子邮件地址 six6rhapsody@gmail.com，或该地址无法接收邮件，因此无法递送您的邮件。
了解详情


</body>
</html>找不到地址
由于系统找不到电子邮件地址 six6rhapsody@gmail.com，或该地址无法接收邮件，因此无法递送您的邮件。

**Comment by necrodiver** [comment]
你这翻墙技术，邮箱是没问题的，可以的话在这里发个百度网盘链接，当然你有其他的链接都行

**Comment by zenyanxiao1** [comment]
> six6rhapsody@gmail.com



> 你这个翻墙技术，邮箱是没问题的，可以在这里发个百度网盘链接，当然你还有其他的链接都行

检查下邮箱吧, 我用自己谷歌给自己163发邮件没问题, 再用自己163给自己谷歌发也没问题,  用谷歌和163给你都发不过去

**Comment by zenyanxiao1** [comment]
> 你这个翻墙技术，邮箱是没问题的，可以在这里发个百度网盘链接，当然你还有其他的链接都行

要不检查下邮箱....我用自己谷歌给自己163发邮件没问题，再用自己163给自己谷歌发也没问题，用谷歌和163给你都发不过去

**Comment by zenyanxiao1** [comment]
> six6rhapsody@gmail.com

https://drive.google.com/file/d/1CR-sKUg4ya5sCndjiPvuTyJrB1e7eMAY/view

**Comment by ChenYingqin** [comment]
解决了不大佬

**Comment by ChenYingqin** [comment]
解决了不，大佬

**Comment by AvaTaylor121** [comment]
大佬，还能用吗，运行一直请求失败，请重启
