### ISSUE TITLE
关于源代码

### ISSUE THREAD

**Issue by fengyelingdu** [necrodiver/HospitalAutoRegister#5]
老哥，这个方便提供源代码么，想学习一下，感谢

**Comment by necrodiver** [comment]
等我把第二版（可视化）开发完了发上来再写个教程吧，加源码

**Comment by fengyelingdu** [comment]
> 等我把第二版（可视化）开发完了发上来再写个教程吧，加源码

非常感谢，刚好准备去北大口腔拔牙，明天试试

**Comment by necrodiver** [comment]
注意别被封号了，老铁，看另一个[issue](https://github.com/necrodiver/HospitalAutoRegister/issues/4)

**Comment by fengyelingdu** [comment]
> 注意别被封号了，老铁，看另一个[issue](https://github.com/necrodiver/HospitalAutoRegister/issues/4)

好的，一个线程，不敢多了，https://bdkq.leanpay.cn/weixin-miniapp-bdkq@cc51073c/api/appointmentInfo/getYyDoctorInfo.json?time=2022-01-08&deptCode=683&tapIndex=0   我抓包看了下，日期和科室这两个参数看懂了，然后那个tapIndex看着又不太像患者id，然后看了下这个get请求好像也没携带患者id

**Comment by fengyelingdu** [comment]
> 注意别被封号了，老铁，看另一个[issue](https://github.com/necrodiver/HospitalAutoRegister/issues/4)

好的，一个线程，不敢多了，https://bdkq.leanpay.cn/weixin-miniapp-bdkq@cc51073c/api/appointmentInfo/getYyDoctorInfo.json?time=2022-01-08&deptCode=683&tapIndex=0   我抓包看了下，日期和科室这两个参数看懂了，然后那个tapIndex看着又不太像患者id，然后看了下这个get请求好像也没携带患者id

> 注意别被封号了，老铁，看另一个[issue](https://github.com/necrodiver/HospitalAutoRegister/issues/4)

在挂号记录页面找到7位patientId了，明天搞一搞，感谢老哥
