### ISSUE TITLE
请求报错

### ISSUE THREAD

**Issue by Aias00** [necrodiver/HospitalAutoRegister#7]
系统环境 m1 macos monterey 12.01
请求未填写 PATIENT_ID，因为之前没挂过号，抓包获取不到

**Comment by Aias00** [comment]
点击挂号记录，在请求体中拿到了PATIENT_ID，不知道是不是这个原因导致的，一会儿12点再试一下

**Comment by necrodiver** [comment]
这两天我就发个源码

**Comment by Aias00** [comment]
> 这两天我就发个源码

辛苦辛苦
