### ISSUE TITLE
login.json返回的加密Body解密求助

### ISSUE THREAD

**Issue by aofalyb** [necrodiver/HospitalAutoRegister#8]
Hi，想请教一下，这个Body加密的方式是什么方式呢？
我尝试了好多种用X-Sign作为Key去解密，但是都失败了，求指点，谢谢！

**Comment by necrodiver** [comment]
哈喽，你可以参考内部源码实现，EncryDecryHelper.go这个文件下DecryStr方法，使用了otto调用了内部wxutil.js的方法，在这里查找ALL的CC方法，其内部js会调用对应的解密方法，调用关系可以看源码（注意大小写），至于具体实现，可以自己研究一下（我觉得没必要耗费精力去看这个，除非你想使用其他语言实现一套），也说过了，wxutil.js是核心代码，不过源码都是已经被压缩了的，方法具体意义都被转义成了标识字母。

**Comment by aofalyb** [comment]
收到~十分感谢~

**Comment by aofalyb** [comment]
Hi，还有一个疑问就是app.ini中
# 用户调用login.json接口返回的值，（必填）
USER_ENCRY = 
这个USER_ENCRY的值就是在解密login.json返回值后，可以从解密后的内容里面找到的对吧？
app.ini其他的值我都可以获取到了，就只差这一个USER_ENCRY 值了。谢谢！
