### ISSUE TITLE
关于构建app内容

### ISSUE THREAD

**Issue by 0xMario27** [necrodiver/HospitalAutoRegister#9]
纯后端工程师，想问下这个app中的vite项目如何构建出dist呢

**Comment by necrodiver** [comment]
哈喽，如果你只是想使用那么按照这个步骤来操作：
1. 进入app文件夹下，使用命令:npm i 或者 yarn install，来安装引用插件（可能需要前置安装npm或者yarn），安装成功会有提示，如果报错也将会有提示，可能是插件问题导致，修复或者重新引用（删除node_modules文件夹、package-lock.json或yarn.lock）；
2. 安装完毕后使用命令:npm run dev，来启动项目查看是否能够启动，成功会在默认浏览器中打开页面（但是不能够访问接口，可以启动go项目，这时就可以访问了，此方法供开发时使用，不用每次测试都打包，但是纯粹的去运行肯定会出问题，因为gin框架引用了本地dist文件夹下的静态文件，无文件就报错了，可以手动注释这部分代码，最后解释这部分技术：做了cors白名单，可以访问go启动的微站点，vite.config.js下有proxy反向代理配置，指向本地10087端口，对应的go项目cors白名单的本地10087）；
3. 如果不想自己修改源码或者测试，使用命令：npm run build，这时就会在dist文件夹下生成打包文件，在go项目在运行及使用就行了；
4. 如果以上都无法操作或者不想折腾，可以看tag的v1.0，有第一版的运行程序供下载，不过第一版的不是很全，有些配置是写死的，也可以魔改当前版本的源码，采用非界面形式，当然我也可以上传一份dist文件夹下的打包文件，抽空上传一下也行；

**Comment by 0xMario27** [comment]
非常感谢您的耐心解答。步骤非常详细。我来实践一下。

**Comment by ccdeville** [comment]
按步骤打包后运行 不加载页面

**Comment by necrodiver** [comment]
你好，首先请先排查步骤中所说的报错及问题，如果都没问题请看下方解决方案：
1. 请查看使用npm run dev启动后，在控制台或者命令行是否有输出对应的本地链接（可点击的，应该是localhost:10087这样的），如果启动报错，那么就说明你的构建存在问题
2. 以上如果未报错，链接无法打开，请查看本地安全策略是否太高？或者被禁用了？（一般开发人员不会禁用本地端口）
3. 如果链接可以打开，但页面空白，可以使用chrome高版本打开，因为此项目前端代码使用了一些高级别语法糖及只有高版本浏览器才能支持的功能，比如web worker（如何查看是否支持，可以在打开的页面上右键检查或者F12来打开控制台，在console栏看是否存在报错，一般都是找不到对应方法）
4. 最后，你的问题描述太泛泛了，我也无法精确定位具体问题，如需要协助解决，请提供详细的问题，如果必要可以新开一个issues

**Comment by 8955107** [comment]
请问作者使用的node是什么版本的呢，我在npm i的过程中一直频繁的报错，已经换了好几个node的版本了。

**Comment by necrodiver** [comment]
你好，猜测你是windows系统，而且没有安装node-gyp，报错应该是gyp问题，如有需要请新开一个issues

**Comment by haogong** [comment]
@necrodiver 您好，我是Mac系统，系统安装了 go，gin, node, npm 都有了。
按你的说明，我做了一些操作，有一些错误，如下：
1. 我用 git clone 你的代码下来，运行 npm i，提示我：ENOENT: no such file or directory， 找不到package.json文件
2. 我运行npm init，创建了一个package.json文件
3. 运行npm run dev或npm run build都提示我 Missing script: "dev"/"build" 这种

我对go语言及环境并不熟，可能是并没有搞清楚运行过程，我的目的只是想运行起来，能麻烦您把过程稍微详细的写一下吗？感谢感谢

**Comment by haogong** [comment]
请问 @necrodiver ，我用npm run dev已经可以打开浏览器，并显示让我输入相关参数，我直接在这个面面用可以吗？
另外，你说的“npm run build”进行编译，倒是编译成功了，但不知道怎么用（我只是想用用，我对go一无所知）
我在你另一个回复里看 go run main.go，不知对不对，但我这里报错：

# golang.org/x/sys/unix
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
/Users/hao/go/pkg/mod/golang.org/x/sys@v0.0.0-20200116001909-b77594299b42/unix/zsyscall_darwin_amd64.go:121:3: too many errors

**Comment by haogong** [comment]
我好像把电脑上默认的 go 1.18 卸载了，再安装 go 1.17 就可以了。
另外界面和调试时的那个界面是一样的。是不是意味着直接用调试那个使用也是可以的。
